"""Email client for sending analysis emails."""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


class EmailClient:
    """Client for sending emails via SMTP SSL."""
    
    def __init__(self, smtp_server: str, smtp_port: int, 
                 sender_email: str, sender_password: str):
        """Initialize email client."""
        self._smtp_server = smtp_server
        self._smtp_port = smtp_port
        self._sender_email = sender_email
        self._sender_password = sender_password
    
    def send_analysis(self, recipients: list[str], content: str, date_str: str) -> bool:
        """Send build opportunity analysis email as HTML."""
        try:
            html_body = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <style>
                    body {{
                        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                        line-height: 1.6;
                        color: #333;
                        max-width: 800px;
                        margin: 0 auto;
                        padding: 20px;
                        background-color: #f5f5f5;
                    }}
                    .header {{
                        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                        color: white;
                        padding: 30px;
                        border-radius: 10px 10px 0 0;
                        text-align: center;
                    }}
                    .header h1 {{
                        margin: 0;
                        font-size: 24px;
                    }}
                    .header p {{
                        margin: 10px 0 0 0;
                        opacity: 0.9;
                    }}
                    .content {{
                        background: white;
                        padding: 30px;
                        border-radius: 0 0 10px 10px;
                        box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                    }}
                    .opportunities {{
                        margin: 20px 0;
                    }}
                    .idea {{
                        background: #f8f9fa;
                        border-left: 4px solid #667eea;
                        padding: 20px;
                        margin-bottom: 20px;
                        border-radius: 5px;
                    }}
                    .idea h3 {{
                        margin-top: 0;
                        color: #667eea;
                        font-size: 20px;
                    }}
                    .idea p {{
                        margin: 10px 0;
                    }}
                    .idea strong {{
                        color: #555;
                    }}
                    .no-ideas {{
                        text-align: center;
                        padding: 40px;
                        color: #999;
                    }}
                    .footer {{
                        text-align: center;
                        margin-top: 30px;
                        padding-top: 20px;
                        border-top: 1px solid #e0e0e0;
                        color: #999;
                        font-size: 14px;
                    }}
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>💡 Build Opportunity Analysis</h1>
                    <p>{date_str}</p>
                </div>
                <div class="content">
                    {content}
                    <div class="footer">
                        <p>Generated by Reddit Build Opportunity Analyzer</p>
                        <p>Powered by AI analysis of top Reddit posts</p>
                    </div>
                </div>
            </body>
            </html>
            """
            
            msg = MIMEMultipart('alternative')
            msg["Subject"] = f"💡 Build Opportunities - {date_str}"
            msg["To"] = ", ".join(recipients)
            msg["From"] = self._sender_email
            
            # Attach HTML content
            html_part = MIMEText(html_body, 'html', 'utf-8')
            msg.attach(html_part)

            with smtplib.SMTP_SSL(self._smtp_server, self._smtp_port) as server:
                server.login(self._sender_email, self._sender_password)
                server.sendmail(self._sender_email, recipients, msg.as_string())
            
            print(f"✅ Email sent to {', '.join(recipients)}\n")
            return True
            
        except Exception as e:
            print(f"❌ Email failed: {e}\n")
            return False
